set(VCPKG_TARGET_ARCHITECTURE wasm32)
set(VCPKG_CRT_LINKAGE static)
set(VCPKG_LIBRARY_LINKAGE static)
set(VCPKG_CMAKE_SYSTEM_NAME WASI)
set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE "/home/toge/vm/wasi-sdk/share/cmake/wasi-sdk-p1.cmake")
