#pragma once

#include "frozenchars/concepts.hpp"
#include "frozenchars/char_pred.hpp"
#include "frozenchars/string.hpp"
#include "frozenchars/freeze.hpp"
#include "frozenchars/string_ops.hpp"
#include "frozenchars/case_conv.hpp"
#include "frozenchars/split.hpp"
#include "frozenchars/multiline.hpp"
#include "frozenchars/encoding.hpp"
#include "frozenchars/color.hpp"
#include "frozenchars/type_parser.hpp"
#include "frozenchars/literals.hpp"
#include "frozenchars/ops.hpp"
#include "frozenchars/format.hpp"
#include "frozenchars/url.hpp"
#include "frozenchars/number_conv.hpp"
#include "frozenchars/wildcard.hpp"
#include "frozenchars/ctre.hpp"
#include "frozenchars/regex_comment.hpp"
#include "frozenchars/map.hpp"
#include "frozenchars/glaze_frozen_map.hpp"
#if defined(__has_include) && __has_include(<glaze/glaze.hpp>)
#include "frozenchars/inja_value.hpp"
#include "frozenchars/inja_function.hpp"
#include "frozenchars/inja_engine.hpp"
#endif
