#!/usr/bin/env python3
"""
frozenchars 単一ヘッダ生成スクリプト (stdlib のみ)

  python3 tools/amalgamate.py                # single_include/frozenchars.hpp + _json.hpp + _freestanding.hpp を生成
  python3 tools/amalgamate.py --check        # 生成結果と既存ファイルの差分検証
  python3 tools/amalgamate.py --stdout       # all_basic 版を標準出力へ

出力は決定的 (時刻スタンプなし)。内容が変わらない限り再生成しても diff は出ない。
"""

from __future__ import annotations

import argparse
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
INCLUDE_ROOT = ROOT / "include"
LICENSE_FILE = ROOT / "LICENSE"

# 正規表現: 行頭空白を許容
RE_INCLUDE_QUOTED = re.compile(r'^\s*#\s*include\s*"([^"]+)"')
RE_INCLUDE_SYSTEM = re.compile(r'^\s*#\s*include\s*<([^>]+)>')
RE_PRAGMA_ONCE = re.compile(r'^\s*#\s*pragma\s+once\b')

HEADER_PREAMBLE = """// frozenchars single header — generated by tools/amalgamate.py
// Source: {entry}
// Do not edit manually. Re-generate with: python3 tools/amalgamate.py{extra}
// Repository: https://github.com/toge/frozenchars
"""


def read_license() -> str:
  if LICENSE_FILE.exists():
    txt = LICENSE_FILE.read_text(encoding="utf-8").strip()
    # 1行コメント化
    lines = ["// " + line if line else "//" for line in txt.splitlines()]
    return "\n".join(lines)
  return "// MIT License — see LICENSE in repository"


def inject_freestanding_define(text: str) -> str:
  """
  通常ヘッダのテキストに FROZENCHARS_WASI_MINIMAL 定義を注入して
  freestanding 単一ヘッダを作る。利用者が追加の -DFROZENCHARS_WASI_MINIMAL を
  付けなくても freestanding モードで使えるようにする。
  # ponytail: 既存の amalgamate 出力を書き換えるだけ。別エントリの再アマルガム不要
  """
  marker = "#pragma once\n"
  if marker in text:
    return text.replace(
      marker,
      marker + "\n#ifndef FROZENCHARS_WASI_MINIMAL\n#define FROZENCHARS_WASI_MINIMAL 1\n#endif\n",
      1,
    )
  return "#ifndef FROZENCHARS_WASI_MINIMAL\n#define FROZENCHARS_WASI_MINIMAL 1\n#endif\n" + text


def resolve(rel: str, visited: set[str]) -> str:
  """
  include/ 相対パス rel のヘッダを再帰的にインライン展開して返す。
  visited は呼び出し間で共有し、同じヘッダを 2 度展開しない。
  システムヘッダは #if ガード付きで出現するため hoist せずそのまま残す
  (重複は各ヘッダの include guard で吸収される)。
  """
  if rel in visited:
    return ""
  visited.add(rel)
  full = INCLUDE_ROOT / rel
  if not full.exists():
    raise FileNotFoundError(f"include not found: {rel}")
  out: list[str] = []
  for line in full.read_text(encoding="utf-8").splitlines():
    m = RE_INCLUDE_QUOTED.match(line)
    if m:
      target = resolve_include_path(rel, m.group(1))
      inlined = resolve(target, visited)
      if inlined:
        out.append(f"// ---- begin {target} ----")
        out.append(inlined)
        out.append(f"// ---- end {target} ----")
      continue
    if RE_PRAGMA_ONCE.match(line):
      continue
    out.append(line)
  return "\n".join(out)


def resolve_include_path(rel: str, inc: str) -> str:
  """#include "inc" (rel 内に出現) を include/ 相対パスへ正規化する。"""
  if inc.startswith("frozenchars/"):
    return inc
  cur_dir = pathlib.Path(rel).parent
  candidate = INCLUDE_ROOT / cur_dir / inc
  try:
    target = str(candidate.resolve().relative_to(INCLUDE_ROOT.resolve()))
  except ValueError:
    target = str(pathlib.PurePosixPath(str(cur_dir / inc).replace("\\", "/")))
  for alt in (target, f"frozenchars/{inc}", f"frozenchars/detail/{inc}"):
    if (INCLUDE_ROOT / alt).exists():
      return alt
  raise FileNotFoundError(f'cannot resolve include "{inc}" in {rel}')


def wrap(body: str, entry_label: str, extra: str = "") -> str:
  parts = [
    "#pragma once",
    "",
    read_license(),
    "",
    HEADER_PREAMBLE.format(entry=entry_label, extra=extra).strip(),
    "",
    "// ---- amalgamated body (system includes are kept inline to preserve #if guards) ----",
    body,
    "",
  ]
  text = "\n".join(parts)
  return text if text.endswith("\n") else text + "\n"


def amalgamate(entry_rel: str) -> str:
  """entry_rel (include/ 相対、例: frozenchars/mod/all_basic.hpp) を単一ヘッダにする。"""
  if not (INCLUDE_ROOT / entry_rel).exists():
    raise FileNotFoundError(f"entry not found: {INCLUDE_ROOT / entry_rel}")
  return wrap(resolve(entry_rel, set()), entry_rel)


def generate_with_json() -> str:
  """json 付き版: all_basic + crush + compress を visited 共有で 1 ファイルにまとめる。"""
  entries = [
    "frozenchars/mod/all_basic.hpp",
    "frozenchars/json/crush.hpp",
    "frozenchars/json/compress.hpp",
  ]
  visited: set[str] = set()
  bodies: list[str] = []
  for e in entries:
    b = resolve(e, visited)
    if b:
      bodies.append(f"// ==== entry: {e} ====")
      bodies.append(b)
  return wrap("\n".join(bodies), " + ".join(entries), " --with-json")


def check_or_write(outputs: list[tuple[pathlib.Path, str]], check: bool) -> int:
  ok = True
  for path, txt in outputs:
    if check:
      if not path.exists():
        print(f"--check: missing {path}", file=sys.stderr)
        ok = False
      elif path.read_text(encoding="utf-8") != txt:
        print(f"--check: {path} differs (run without --check to regenerate)", file=sys.stderr)
        ok = False
      else:
        print(f"--check: {path} ok")
    else:
      path.parent.mkdir(parents=True, exist_ok=True)
      path.write_text(txt, encoding="utf-8")
      print(f"wrote {path} ({len(txt.splitlines())} lines, {len(txt.encode('utf-8'))} bytes)")
  return 0 if ok else 1


def main() -> int:
  p = argparse.ArgumentParser(description="frozenchars single header amalgamation")
  p.add_argument("--with-json", action="store_true", help="(互換用、常に有効) json variant も生成する")
  p.add_argument("--check", action="store_true", help="verify existing files match generated output")
  p.add_argument("--stdout", action="store_true", help="print to stdout instead of files")
  p.add_argument("--entry", default="frozenchars/mod/all_basic.hpp", help="custom entry (relative to include/)")
  p.add_argument("--output", default="single_include/frozenchars.hpp", help="custom output path")
  args = p.parse_args()

  if args.stdout:
    sys.stdout.write(amalgamate(args.entry))
    return 0

  # --entry がデフォルト以外ならそのエントリだけを生成/検証する
  if args.entry != "frozenchars/mod/all_basic.hpp":
    return check_or_write([(ROOT / args.output, amalgamate(args.entry))], args.check)

  std_txt = amalgamate("frozenchars/mod/all_basic.hpp")
  freestanding_txt = inject_freestanding_define(std_txt).replace(
    "Source: frozenchars/mod/all_basic.hpp",
    "Source: frozenchars/mod/all_basic.hpp (freestanding)",
  ).replace(
    "python3 tools/amalgamate.py",
    "python3 tools/amalgamate.py (freestanding)",
    1,
  )
  outputs = [
    (ROOT / "single_include/frozenchars.hpp", std_txt),
    (ROOT / "single_include/frozenchars_json.hpp", generate_with_json()),
    (ROOT / "single_include/frozenchars_freestanding.hpp", freestanding_txt),
  ]
  return check_or_write(outputs, args.check)


if __name__ == "__main__":
  raise SystemExit(main())
