#!/usr/bin/env python3
"""
frozenchars 単一ヘッダ生成スクリプト (stdlib のみ)

  python3 tools/amalgamate.py                # single_include/frozenchars.hpp (all_basic)
  python3 tools/amalgamate.py --with-json    # 上記 + single_include/frozenchars_json.hpp
  python3 tools/amalgamate.py --check        # 生成結果と既存ファイルの差分検証
  python3 tools/amalgamate.py --stdout       # 標準出力へ
"""

from __future__ import annotations

import argparse
import datetime
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
INCLUDE_ROOT = ROOT / "include"
LICENSE_FILE = ROOT / "LICENSE"

# 正規表現: 行頭空白を許容
RE_INCLUDE_QUOTED = re.compile(r'^\s*#\s*include\s*"([^"]+)"')
RE_INCLUDE_SYSTEM = re.compile(r'^\s*#\s*include\s*<([^>]+)>')
RE_PRAGMA_ONCE = re.compile(r'^\s*#\s*pragma\s+once\b')

HEADER_PREAMBLE = """// frozenchars single header — generated by tools/amalgamate.py
// Source: {entry}
// Do not edit manually. Re-generate with: python3 tools/amalgamate.py{extra}
// Repository: https://github.com/anomalyco/frozenchars
// Generated: {when} UTC
"""


def read_license() -> str:
  if LICENSE_FILE.exists():
    txt = LICENSE_FILE.read_text(encoding="utf-8").strip()
    # 1行コメント化
    lines = ["// " + line if line else "//" for line in txt.splitlines()]
    return "\n".join(lines)
  return "// MIT License — see LICENSE in repository"


def amalgamate(entry_rel: str) -> str:
  """
  entry_rel: include/ からの相対パス (例: frozenchars/mod/all_basic.hpp)
  戻り値: 単一ヘッダのテキスト
  """
  visited: set[str] = set()

  # entry の存在確認
  entry_path = INCLUDE_ROOT / entry_rel
  if not entry_path.exists():
    raise FileNotFoundError(f"entry not found: {entry_path}")

  def resolve(rel: str) -> str:
    if rel in visited:
      return ""
    visited.add(rel)
    full = INCLUDE_ROOT / rel
    if not full.exists():
      raise FileNotFoundError(f"include not found: {rel} (from {full})")
    raw = full.read_text(encoding="utf-8")
    out_lines: list[str] = []
    for line in raw.splitlines():
      m = RE_INCLUDE_QUOTED.match(line)
      if m:
        inc = m.group(1)
        # inc を INCLUDE_ROOT からの相対パスに正規化
        if inc.startswith("frozenchars/"):
          target = inc
        else:
          cur_dir = pathlib.Path(rel).parent
          candidate = (INCLUDE_ROOT / cur_dir / inc)
          try:
            cand_resolved = candidate.resolve()
            inc_root_resolved = INCLUDE_ROOT.resolve()
            target = str(cand_resolved.relative_to(inc_root_resolved))
          except Exception:
            target = str(cur_dir / inc).replace("\\", "/")
            target = str(pathlib.PurePosixPath(target))
          if not (INCLUDE_ROOT / target).exists():
            alt = f"frozenchars/{inc}"
            if (INCLUDE_ROOT / alt).exists():
              target = alt
            else:
              alt2 = f"frozenchars/detail/{inc}"
              if (INCLUDE_ROOT / alt2).exists():
                target = alt2
              else:
                raise FileNotFoundError(f"cannot resolve include \"{inc}\" in {rel} -> tried {target}")
        inlined = resolve(target)
        if inlined:
          out_lines.append(f"// ---- begin {target} ----")
          out_lines.append(inlined)
          out_lines.append(f"// ---- end {target} ----")
        continue

      # システムヘッダはガード付き(#if)で出現するため hoist せずインライン保持する
      # (例: #if defined(__aarch64__) -> #include <arm_acle.h>)
      # 重複は各ヘッダの include guard で吸収されるためそのまま出力する
      if RE_PRAGMA_ONCE.match(line):
        continue

      out_lines.append(line)

    return "\n".join(out_lines)

  body = resolve(entry_rel)

  extra = " --with-json" if "json" in entry_rel else ""
  preamble = HEADER_PREAMBLE.format(entry=entry_rel, extra=extra, when=datetime.datetime.utcnow().isoformat())
  license_block = read_license()

  parts: list[str] = []
  parts.append("#pragma once")
  parts.append("")
  parts.append(license_block)
  parts.append("")
  parts.append(preamble.strip())
  parts.append("")
  parts.append("// ---- amalgamated body (system includes are kept inline to preserve #if guards) ----")
  parts.append(body)
  parts.append("")
  text = "\n".join(parts)
  if not text.endswith("\n"):
    text += "\n"
  return text


def generate_with_json() -> tuple[str, str]:
  """
  json 付き版は all_basic + crush + compress を順に resolve して1ファイルにまとめる。
  visited を共有して重複排除。システムヘッダは #if ガード保持のため inline のまま。
  """
  visited: set[str] = set()

  def resolve_multi(rel: str) -> str:
    if rel in visited:
      return ""
    visited.add(rel)
    full = INCLUDE_ROOT / rel
    if not full.exists():
      raise FileNotFoundError(f"include not found: {rel}")
    raw = full.read_text(encoding="utf-8")
    out: list[str] = []
    for line in raw.splitlines():
      m = RE_INCLUDE_QUOTED.match(line)
      if m:
        inc = m.group(1)
        if inc.startswith("frozenchars/"):
          target = inc
        else:
          cur_dir = pathlib.Path(rel).parent
          candidate = (INCLUDE_ROOT / cur_dir / inc)
          try:
            target = str(candidate.resolve().relative_to(INCLUDE_ROOT.resolve()))
          except Exception:
            target = str(cur_dir / inc).replace("\\", "/")
            target = str(pathlib.PurePosixPath(target))
          if not (INCLUDE_ROOT / target).exists():
            alt = f"frozenchars/{inc}"
            if (INCLUDE_ROOT / alt).exists():
              target = alt
            else:
              alt2 = f"frozenchars/detail/{inc}"
              if (INCLUDE_ROOT / alt2).exists():
                target = alt2
              else:
                raise FileNotFoundError(f"cannot resolve \"{inc}\" in {rel}")
        inlined = resolve_multi(target)
        if inlined:
          out.append(f"// ---- begin {target} ----")
          out.append(inlined)
          out.append(f"// ---- end {target} ----")
        continue
      if RE_PRAGMA_ONCE.match(line):
        continue
      out.append(line)
    return "\n".join(out)

  entries = [
    "frozenchars/mod/all_basic.hpp",
    "frozenchars/json/crush.hpp",
    "frozenchars/json/compress.hpp",
  ]
  bodies: list[str] = []
  for e in entries:
    b = resolve_multi(e)
    if b:
      bodies.append(f"// ==== entry: {e} ====")
      bodies.append(b)

  body = "\n".join(bodies)
  preamble = HEADER_PREAMBLE.format(
    entry=" + ".join(entries),
    extra=" --with-json",
    when=datetime.datetime.utcnow().isoformat(),
  )
  license_block = read_license()
  parts: list[str] = []
  parts.append("#pragma once")
  parts.append("")
  parts.append(license_block)
  parts.append("")
  parts.append(preamble.strip())
  parts.append("")
  parts.append("// ---- amalgamated body (system includes are kept inline to preserve #if guards) ----")
  parts.append(body)
  parts.append("")
  text = "\n".join(parts)
  if not text.endswith("\n"):
    text += "\n"
  return text, ""


def main() -> int:
  p = argparse.ArgumentParser(description="frozenchars single header amalgamation")
  p.add_argument("--with-json", action="store_true", help="also generate json variant")
  p.add_argument("--check", action="store_true", help="verify existing files match generated output")
  p.add_argument("--stdout", action="store_true", help="print to stdout instead of files")
  p.add_argument("--entry", default="frozenchars/mod/all_basic.hpp", help="custom entry (relative to include/)")
  p.add_argument("--output", default="single_include/frozenchars.hpp", help="custom output path")
  args = p.parse_args()

  if args.stdout:
    txt = amalgamate(args.entry)
    sys.stdout.write(txt)
    return 0

  # 標準
  out_path = ROOT / args.output
  # --entry がデフォルト以外ならそちらを優先
  if args.entry != "frozenchars/mod/all_basic.hpp":
    txt = amalgamate(args.entry)
    if args.check:
      if not out_path.exists():
        print(f"--check: {out_path} not found", file=sys.stderr)
        return 1
      existing = out_path.read_text(encoding="utf-8")
      # 生成時刻行を除外して比較
      def norm(s: str) -> str:
        return re.sub(r"Generated:.*", "Generated:", s)
      if norm(existing) != norm(txt):
        print(f"--check: {out_path} differs", file=sys.stderr)
        return 1
      print(f"--check: {out_path} ok")
      return 0
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(txt, encoding="utf-8")
    print(f"wrote {out_path} ({len(txt.splitlines())} lines)")
    return 0

  # デフォルト: all_basic
  std_txt = amalgamate("frozenchars/mod/all_basic.hpp")
  json_txt, _ = generate_with_json()

  outputs = [
    (ROOT / "single_include/frozenchars.hpp", std_txt),
    (ROOT / "single_include/frozenchars_json.hpp", json_txt),
  ]
  # --with-json なしでも両方生成するのがデフォルト（怠惰: 1回で両方揃う）
  # 明示的に --with-json のみ要求された場合は両方、そうでなければ標準のみに絞るかは
  # 運用で選べる。ここではデフォルトで両方出す（CI --check でも両方検証できる）
  targets = outputs if args.with_json or not args.check else outputs
  # --with-json が無い通常実行でも両方出す（Wandbox用に揃えておく方が親切）
  # ただし --check なしの通常実行は両方生成
  if not args.with_json and not args.check:
    # 通常: 両方生成（サイズ差は数千行、コスト無視できる）
    targets = outputs

  # --check モード
  if args.check:
    ok = True
    for path, txt in targets:
      if not path.exists():
        print(f"--check: missing {path}", file=sys.stderr)
        ok = False
        continue
      existing = path.read_text(encoding="utf-8")
      def norm(s: str) -> str:
        return re.sub(r"Generated:.*", "Generated:", s)
      if norm(existing) != norm(txt):
        print(f"--check: {path} differs (run without --check to regenerate)", file=sys.stderr)
        ok = False
      else:
        print(f"--check: {path} ok")
    return 0 if ok else 1

  for path, txt in targets:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(txt, encoding="utf-8")
    print(f"wrote {path} ({len(txt.splitlines())} lines, {len(txt.encode('utf-8'))} bytes)")

  return 0


if __name__ == "__main__":
  raise SystemExit(main())
